# Generated by Django 5.0.1 on 2024-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.URLField(blank=True, max_length=1000, verbose_name='feature photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep',
            field=models.IntegerField(blank=True, null=True, verbose_name='prep time'),
        ),
    ]
