# Generated by Django 5.0.1 on 2024-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_place_products_alter_product_type_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, '0% beer'), (2, '0% cider'), (3, '0% wine'), (4, '0% champagne'), (5, '0% gin'), (6, '0% rum'), (7, '0% vodka'), (8, '0% tequila'), (9, '0% whiskey')], default=1),
        ),
    ]
