# Generated by Django 5.0.1 on 2024-01-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=1000, verbose_name='ingredients (separate by commas)'),
        ),
    ]
