# Generated by Django 5.0.1 on 2024-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_maps',
            field=models.CharField(blank=True, max_length=300, verbose_name='address'),
        ),
    ]
