# Generated by Django 5.0.1 on 2024-01-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_place_google_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='google_maps',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
