# Generated by Django 5.0.1 on 2024-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='uploaded_img',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_photos/'),
        ),
    ]
