# Generated by Django 5.0.1 on 2024-01-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_recipe_img_alter_recipe_uploaded_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
