# Generated by Django 5.0.1 on 2024-01-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='or paste photo url'),
        ),
    ]
